apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: claude-code-secrets
  namespace: gzc-trading
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ae954be9-9a46-4085-849a-191d8884119c"
    keyvaultName: "gzc-finma-keyvault"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: ANTHROPIC-API-KEY
          objectType: secret
          objectAlias: api-key
    tenantId: "8274c97d-de9d-4328-98cf-2d4ee94bf104"